version: "3.9"

services:
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

  app:
    build:
      context: .
    restart: always
    env_file:
      - .env

volumes:
  mysql: null
  mysql_config: null
